--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : Apr 14 2013 19:25
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'Claim'   
--
DROP TABLE Claim
/
--
-- Drop Table    : 'Property'   
--
DROP TABLE Property
/
--
-- Drop Table    : 'Life'   
--
DROP TABLE Life
/
--
-- Drop Table    : 'Customers_Policy'   
--
DROP TABLE Customers_Policy
/
--
-- Drop Table    : 'Policy'   
--
DROP TABLE Policy
/
--
-- Drop Table    : 'Customer'   
--
DROP TABLE Customer
/
exit;

