--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : Apr 04 2013 15:07
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'Claims'   
--
DROP TABLE Claims
/
--
-- Drop Table    : 'Property'   
--
DROP TABLE Property
/
--
-- Drop Table    : 'Life'   
--
DROP TABLE Life
/
--
-- Drop Table    : 'Customers_Policies'   
--
DROP TABLE Customers_Policies
/
--
-- Drop Table    : 'Policies'   
--
DROP TABLE Policies
/
--
-- Drop Table    : 'Customer'   
--
DROP TABLE Customer
/
exit;

