--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : Mar 17 2013 15:00
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Customer'   
-- Customer_ID     :  
-- First_Name      :  
-- Last_Name       :  
-- Birth_Date      :  
-- Gender          :  
-- Address         :  
-- Phone           :  
-- Email           :  
--
CREATE TABLE Customer (
    Customer_ID    NUMBER(38) NOT NULL,
    First_Name     VARCHAR2(20) NOT NULL,
    Last_Name      VARCHAR2(20) NOT NULL,
    Birth_Date     DATE NOT NULL,
    Gender         NUMBER(1) NOT NULL,
    Address        VARCHAR2(100) NOT NULL,
    Phone          VARCHAR2(20) NOT NULL,
    Email          VARCHAR2(100) NOT NULL,
CONSTRAINT pk_Customer PRIMARY KEY (Customer_ID))
/


--
-- Create Table    : 'Policies'   
-- Policy_ID       :  
-- Description     :  
-- Price           :  
-- Renewal_Duration :  
--
CREATE TABLE Policies (
    Policy_ID      NUMBER(38) NOT NULL,
    Description    LONG NOT NULL,
    Price          NUMBER(38) NOT NULL,
    Renewal_Duration NUMBER(38) NOT NULL,
CONSTRAINT pk_Policies PRIMARY KEY (Policy_ID))
/


--
-- Create Table    : 'Claims'   
-- Claim_ID        :  
-- Claim_Date      :  
-- Description     :  
-- Amount          :  
-- Status          :  
-- Result          :  
-- Settlement_Date :  
--
CREATE TABLE Claims (
    Claim_ID       NUMBER(38) NOT NULL,
    Claim_Date     DATE NOT NULL,
    Description    LONG NOT NULL,
    Amount         NUMBER(38) NOT NULL,
    Status         NUMBER(1),
    Result         LONG,
    Settlement_Date DATE,
CONSTRAINT pk_Claims PRIMARY KEY (Claim_ID))
/


--
-- Create Table    : 'Customers_Policies'   
-- Start_Date      :  
-- Customer_ID     :  (references Customer.Customer_ID)
-- Policy_ID       :  (references Policies.Policy_ID)
-- End_Date        :  
-- Bonus           :  
-- Details         :  
--
CREATE TABLE Customers_Policies (
    Start_Date     DATE NOT NULL,
    Customer_ID    NUMBER(38) NOT NULL,
    Policy_ID      NUMBER(38) NOT NULL,
    End_Date       DATE NOT NULL,
    Bonus          FLOAT NOT NULL,
    Details        LONG,
CONSTRAINT pk_Customers_Policies PRIMARY KEY (Customer_ID,Policy_ID),
CONSTRAINT fk_Customers_Policies FOREIGN KEY (Customer_ID)
    REFERENCES Customer (Customer_ID)
    ON DELETE CASCADE,
CONSTRAINT fk_Customers_Policies2 FOREIGN KEY (Policy_ID)
    REFERENCES Policies (Policy_ID)
    ON DELETE CASCADE)
/


--
-- Create Table    : 'Life'   
-- Policy_ID       :  (references Policies.Policy_ID)
-- Occupation_Code :  
-- Danger_Indicator :  
--
CREATE TABLE Life (
    Policy_ID      NUMBER(38) NOT NULL,
    Occupation_Code NUMBER(38) NOT NULL,
    Danger_Indicator FLOAT NOT NULL,
CONSTRAINT pk_Life PRIMARY KEY (Policy_ID),
CONSTRAINT fk_Life FOREIGN KEY (Policy_ID)
    REFERENCES Policies (Policy_ID))
/


--
-- Create Table    : 'Property'   
-- Policy_ID       :  (references Policies.Policy_ID)
-- Property_Code   :  
-- Age_Of_Property :  
-- Property_Value  :  
--
CREATE TABLE Property (
    Policy_ID      NUMBER(38) NOT NULL,
    Property_Code  NUMBER(1) NOT NULL,
    Age_Of_Property NUMBER(38) NOT NULL,
    Property_Value NUMBER(38) NOT NULL,
CONSTRAINT pk_Property PRIMARY KEY (Policy_ID),
CONSTRAINT fk_Property FOREIGN KEY (Policy_ID)
    REFERENCES Policies (Policy_ID))
/


--
-- Permissions for: 'public'
--
GRANT ALL ON Customer TO public
/
GRANT ALL ON Policies TO public
/
GRANT ALL ON Claims TO public
/
GRANT ALL ON Customers_Policies TO public
/
GRANT ALL ON Life TO public
/
GRANT ALL ON Property TO public
/

exit;

