<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Claims.aspx.cs" Inherits="InsuranceSite.Claims" %>
<asp:Content ID="mainContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="tableGridView" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="CLAIM_ID" 
        DataSourceID="OraInsurance" AllowPaging="True" CellPadding="4" 
        ForeColor="#333333" GridLines="None" AllowSorting="True" 
        AutoGenerateSelectButton="True" style="width: 100%;" 
        onpageindexchanged="rowIndexZero">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="CLAIM_ID" 
                HeaderText="CLAIM_ID" ReadOnly="True" 
                SortExpression="CLAIM_ID" />
            <asp:BoundField DataField="CUSTOMERS_POLICY_ID" ReadOnly="True" HeaderText="CUSTOMERS_POLICY_ID" 
                SortExpression="CUSTOMERS_POLICY_ID" />
            <asp:BoundField DataField="CLAIM_DATE" HeaderText="CLAIM_DATE" 
                SortExpression="CLAIM_DATE" />
            <asp:BoundField DataField="DESCRIPTION" HeaderText="DESCRIPTION" 
                SortExpression="DESCRIPTION" />
            <asp:BoundField DataField="AMOUNT" HeaderText="AMOUNT" 
                SortExpression="AMOUNT" />
            <asp:BoundField DataField="STATUS" HeaderText="STATUS" 
                SortExpression="STATUS" />
            <asp:BoundField DataField="RESULT" HeaderText="RESULT" 
                SortExpression="RESULT" />
            <asp:BoundField DataField="SETTLEMENT_DATE" HeaderText="SETTLEMENT_DATE" 
                SortExpression="SETTLEMENT_DATE" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerSettings FirstPageText="First" LastPageText="Last" PageButtonCount="4" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <asp:SqlDataSource ID="OraInsurance" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>" 
        ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>"        SelectCommand="select * from claim" >
    </asp:SqlDataSource>

    <asp:DetailsView ID="rowDetailsView" runat="server" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateInsertButton="True" CellPadding="4" ForeColor="#333333" 
        GridLines="None" Height="50px" Width="100%" 
        DataSourceID="GridviewSelectedRow" 
        DataKeyNames="CLAIM_ID" AutoGenerateRows="False" >
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
        <EditRowStyle BackColor="#999999" />
        <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
        <Fields>
            <asp:BoundField   DataField="CLAIM_ID" HeaderText="CLAIM_ID" ReadOnly="True" />
            <asp:BoundField   DataField="CUSTOMERS_POLICY_ID" 
                HeaderText="CUSTOMERS_POLICY_ID" ReadOnly="True" />
            <asp:BoundField   DataField="CLAIM_DATE" HeaderText="CLAIM_DATE" />
            <asp:BoundField   DataField="DESCRIPTION" HeaderText="DESCRIPTION" />
            <asp:BoundField   DataField="AMOUNT" HeaderText="AMOUNT" />
            <asp:BoundField   DataField="STATUS" HeaderText="STATUS" />
            <asp:BoundField   DataField="RESULT" HeaderText="RESULT" />
            <asp:BoundField   DataField="SETTLEMENT_DATE" HeaderText="SETTLEMENT_DATE" />
        </Fields>
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
    </asp:DetailsView>
    <asp:SqlDataSource ID="GridviewSelectedRow" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>" 
        ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>" 
        SelectCommand="select * from claim where claim_id = :claim_id" 
        UpdateCommand="update claim set CLAIM_DATE=:CLAIM_DATE, DESCRIPTION=:DESCRIPTION, AMOUNT=:AMOUNT, STATUS=:STATUS, RESULT=:RESULT, SETTLEMENT_DATE=:SETTLEMENT_DATE where claim_id=:claim_id" 
        DeleteCommand="delete from claim where claim_id = :claim_id" 
        InsertCommand="insert into claim (claim_id, CUSTOMERS_POLICY_ID, CLAIM_DATE, DESCRIPTION, AMOUNT, STATUS, RESULT, SETTLEMENT_DATE) values (:claim_id, :CUSTOMERS_POLICY_ID, :CLAIM_DATE, :DESCRIPTION, :AMOUNT, :STATUS, :RESULT, :SETTLEMENT_DATE)" 
        onupdated="updateOraInsurance" ondeleted="updateOraInsurance" 
        oninserted="updateOraInsurance" onselected="updateOraInsurance">
        <SelectParameters>
            <asp:ControlParameter Name="claim_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </SelectParameters>
        <DeleteParameters>
              <asp:ControlParameter Name="claim_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter Name="claim_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="CLAIM_DATE" Type="DateTime" />
            <asp:Parameter Name="DESCRIPTION" Type="String" />
            <asp:Parameter Name="AMOUNT" Type="Decimal" />
            <asp:Parameter Name="STATUS" Type="Decimal" />
            <asp:Parameter Name="RESULT" Type="String" />
            <asp:Parameter Name="SETTLEMENT_DATE" Type="DateTime" />
        </UpdateParameters>
        <InsertParameters>
            <asp:ControlParameter Name="claim_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="customers_policy_id" Type="Decimal" />
            <asp:Parameter Name="CLAIM_DATE" Type="DateTime" />
            <asp:Parameter Name="DESCRIPTION" Type="String" />
            <asp:Parameter Name="AMOUNT" Type="Decimal" />
            <asp:Parameter Name="STATUS" Type="Decimal" />
            <asp:Parameter Name="RESULT" Type="String" />
            <asp:Parameter Name="SETTLEMENT_DATE" Type="DateTime" />
        </InsertParameters>
    </asp:SqlDataSource>
</asp:Content>
