<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="PropertyPolicies.aspx.cs" Inherits="InsuranceSite.PropertyPolicies" %>
<asp:Content ID="Content" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="tableGridView" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="Policy_ID" 
        DataSourceID="OraInsurance" AllowPaging="True" CellPadding="4" 
        ForeColor="#333333" GridLines="None" AllowSorting="True" 
        AutoGenerateSelectButton="True" style="width: 100%;" 
        onpageindexchanged="rowIndexZero">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="POLICY_ID" HeaderText="ID" ReadOnly="True" 
                SortExpression="POLICY_ID" />
            <asp:BoundField DataField="DESCRIPTION" HeaderText="DESCRIPTION" 
                SortExpression="DESCRIPTION" />
            <asp:BoundField DataField="PRICE" HeaderText="PRICE" SortExpression="PRICE" />
            <asp:BoundField DataField="RENEWAL_DURATION" HeaderText="RENEWAL DURATION" 
                SortExpression="RENEWAL_DURATION" />
            <asp:BoundField DataField="PROPERTY_CODE" HeaderText="PROPERTY CODE" 
                SortExpression="PROPERTY_CODE" />
            <asp:BoundField DataField="AGE_OF_PROPERTY" HeaderText="AGE OF PROPERTY" 
                SortExpression="AGE_OF_PROPERTY" />
            <asp:BoundField DataField="PROPERTY_VALUE" HeaderText="PROPERTY VALUE" 
                SortExpression="PROPERTY_VALUE" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerSettings FirstPageText="First" LastPageText="Last" PageButtonCount="4" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <asp:SqlDataSource ID="OraInsurance" runat="server" 
    ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>" 
    ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>" 
    SelectCommand="select * from policy natural join property">
    </asp:SqlDataSource>

    <asp:DetailsView ID="rowDetailsView" runat="server" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateInsertButton="True" CellPadding="4" ForeColor="#333333" 
        GridLines="None" Height="50px" Width="100%" 
        DataSourceID="GridviewSelectedRow" 
        DataKeyNames="POLICY_ID" >
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
        <EditRowStyle BackColor="#999999" />
        <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
        
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
    </asp:DetailsView>
    <asp:SqlDataSource ID="GridviewSelectedRow" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>" 
        ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>" 
        SelectCommand="select * from policy natural join property where policy_id = :policy_id" 
        UpdateCommandType = "StoredProcedure"
        UpdateCommand="updatePropertyPolicy" 
        DeleteCommandType = "StoredProcedure"
        DeleteCommand="deletePropertyPolicy" 
        InsertCommandType = "StoredProcedure"
        InsertCommand="insertPropertyPolicy"
        onupdated="updateOraInsurance" onupdating="SqlStreams_OnUpdating" 
        ondeleted="updateOraInsurance" ondeleting="SqlStreams_OnUpdating" 
        oninserted="updateOraInsurance" oninserting="SqlStreams_OnUpdating">
        <SelectParameters>
            <asp:ControlParameter Name="policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </SelectParameters>
        <DeleteParameters>
            <asp:ControlParameter Name="policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter Name="policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="description" Type="String" />
            <asp:Parameter Name="price" Type="Decimal" />
            <asp:Parameter Name="renewal_duration" Type="Decimal" />
            <asp:Parameter Name="property_code" Type="Decimal" />
            <asp:Parameter Name="age_of_property" Type="Decimal" />
            <asp:Parameter Name="property_value" Type="Decimal" />
        </UpdateParameters>
        <InsertParameters>
              <asp:ControlParameter Name="policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="description" Type="String" />
            <asp:Parameter Name="price" Type="Decimal" />
            <asp:Parameter Name="renewal_duration" Type="Decimal" />
            <asp:Parameter Name="property_code" Type="Decimal" />
            <asp:Parameter Name="age_of_property" Type="Decimal" />
            <asp:Parameter Name="property_value" Type="Decimal" />
        </InsertParameters>
    </asp:SqlDataSource>
</asp:Content>
