<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CustomersPolicies.aspx.cs" Inherits="InsuranceSite.CustomersPolicies" %>
<asp:Content ID="mainContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="tableGridView" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="CUSTOMERS_POLICY_ID" 
        DataSourceID="OraInsurance" AllowPaging="True" CellPadding="4" 
        ForeColor="#333333" GridLines="None" AllowSorting="True" 
        AutoGenerateSelectButton="True" style="width: 100%;" 
        onpageindexchanged="rowIndexZero">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="CUSTOMERS_POLICY_ID" 
                HeaderText="ID" ReadOnly="True" 
                SortExpression="CUSTOMERS_POLICY_ID" />
            <asp:BoundField DataField="CUSTOMER_ID" HeaderText="CUSTOMER ID" ReadOnly="True" SortExpression="CUSTOMER_ID" />
            <asp:BoundField DataField="POLICY_ID" HeaderText="POLICY ID" ReadOnly="True" SortExpression="POLICY_ID" />
            <asp:BoundField DataField="START_DATE" HeaderText="START DATE" 
                SortExpression="START_DATE" DataFormatString="{0:dd MMMM yyyy}" />
            <asp:BoundField DataField="END_DATE" HeaderText="END DATE" 
                SortExpression="END_DATE" DataFormatString="{0:dd MMMM yyyy}" />
            <asp:BoundField DataField="BONUS" HeaderText="BONUS" 
                SortExpression="BONUS" />
            <asp:BoundField DataField="DETAILS" HeaderText="DETAILS" 
                SortExpression="DETAILS" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerSettings FirstPageText="First" LastPageText="Last" PageButtonCount="4" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <asp:SqlDataSource ID="OraInsurance" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>" 
        ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>" 
        SelectCommand="select * from customers_policy" >
    </asp:SqlDataSource>

    <asp:DetailsView ID="rowDetailsView" runat="server" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateInsertButton="True" CellPadding="4" ForeColor="#333333" 
        GridLines="None" Height="50px" Width="100%" 
        DataSourceID="GridviewSelectedRow" 
        DataKeyNames="CUSTOMERS_POLICY_ID" AutoGenerateRows="False" >
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
        <EditRowStyle BackColor="#999999" />
        <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
        <Fields>
            <asp:BoundField DataField="CUSTOMERS_POLICY_ID" 
                HeaderText="ID" ReadOnly="True" 
                SortExpression="CUSTOMERS_POLICY_ID" />
            <asp:BoundField DataField="CUSTOMER_ID" HeaderText="CUSTOMER ID" ReadOnly="True" SortExpression="CUSTOMER_ID" />
            <asp:BoundField DataField="POLICY_ID" HeaderText="POLICY ID" ReadOnly="True" SortExpression="POLICY_ID" />
            <asp:BoundField DataField="START_DATE" HeaderText="START DATE" 
                SortExpression="START_DATE" DataFormatString="{0:dd MMMM yyyy}" />
            <asp:BoundField DataField="END_DATE" HeaderText="END DATE" 
                SortExpression="END_DATE" DataFormatString="{0:dd MMMM yyyy}" />
            <asp:BoundField DataField="BONUS" HeaderText="BONUS" 
                SortExpression="BONUS" />
            <asp:BoundField DataField="DETAILS" HeaderText="DETAILS" 
                SortExpression="DETAILS" />
        </Fields>
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
    </asp:DetailsView>
    <asp:SqlDataSource ID="GridviewSelectedRow" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>" 
        
        ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>"        SelectCommand="select * from customers_policy where customers_policy_id = :customers_policy_id" 
        UpdateCommand="update customers_policy set START_DATE=:START_DATE, END_DATE=:END_DATE, BONUS=:BONUS, DETAILS=:DETAILS where customers_policy_id=:customers_policy_id" 
        DeleteCommand="delete from customers_policy where customers_policy_id = :customers_policy_id" 
        InsertCommand="insert into customers_policy (customers_policy_id, CUSTOMER_ID, POLICY_ID, START_DATE, END_DATE, BONUS, DETAILS) values (:customers_policy_id, :CUSTOMER_ID, :POLICY_ID, :START_DATE, :END_DATE, :BONUS, :DETAILS)" 
        onupdated="updateOraInsurance" ondeleted="updateOraInsurance" 
        oninserted="updateOraInsurance" onselected="updateOraInsurance">
        <SelectParameters>
            <asp:ControlParameter Name="customers_policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </SelectParameters>
        <DeleteParameters>
              <asp:ControlParameter Name="customers_policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter Name="customers_policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="START_DATE" Type="DateTime" />
            <asp:Parameter Name="END_DATE" Type="DateTime" />
            <asp:Parameter Name="BONUS" Type="Decimal" />
            <asp:Parameter Name="DETAILS" Type="String" />
        </UpdateParameters>
        <InsertParameters>
            <asp:ControlParameter Name="customers_policy_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="customer_id" Type="Decimal" />
            <asp:Parameter Name="policy_id" Type="Decimal" />
            <asp:Parameter Name="START_DATE" Type="DateTime" />
            <asp:Parameter Name="END_DATE" Type="DateTime" />
            <asp:Parameter Name="BONUS" Type="Decimal" />
            <asp:Parameter Name="DETAILS" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
</asp:Content>