<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Customers.aspx.cs" Inherits="InsuranceSite.Customers" %>
<asp:Content ID="mainContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="tableGridView" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="CUSTOMER_ID" 
        DataSourceID="OraInsurance" AllowPaging="True" CellPadding="4" 
        ForeColor="#333333" GridLines="None" AllowSorting="True" 
        AutoGenerateSelectButton="True" style="width: 100%;" 
        onpageindexchanged="rowIndexZero">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="CUSTOMER_ID" 
                HeaderText="ID" ReadOnly="True" 
                SortExpression="CUSTOMER_ID" />
            <asp:BoundField DataField="FIRST_NAME" HeaderText="FIRST NAME" 
                SortExpression="FIRST_NAME" />
            <asp:BoundField DataField="LAST_NAME" HeaderText="LAST NAME" 
                SortExpression="LAST_NAME" />
            <asp:BoundField DataField="BIRTH_DATE" HeaderText="BIRTH DATE" 
                SortExpression="BIRTH_DATE" DataFormatString="{0:dd MMMM yyyy}" />
            <asp:BoundField DataField="GENDER" HeaderText="GENDER" 
                SortExpression="GENDER" />
            <asp:BoundField DataField="ADDRESS" HeaderText="ADDRESS" 
                SortExpression="ADDRESS" />
            <asp:BoundField DataField="PHONE" HeaderText="PHONE" 
                SortExpression="PHONE" />
            <asp:BoundField DataField="EMAIL" HeaderText="EMAIL" SortExpression="EMAIL" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerSettings FirstPageText="First" LastPageText="Last" PageButtonCount="4" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <asp:SqlDataSource ID="OraInsurance" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>"        
        ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>" 
        SelectCommand="select * from customer" >
    </asp:SqlDataSource>

    <asp:DetailsView ID="rowDetailsView" runat="server" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateInsertButton="True" CellPadding="4" ForeColor="#333333" 
        GridLines="None" Height="50px" Width="100%" 
        DataSourceID="GridviewSelectedRow" 
        DataKeyNames="CUSTOMER_ID" oniteminserting="oninsert" >
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
        <EditRowStyle BackColor="#999999" />
        <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
    </asp:DetailsView>
    <asp:SqlDataSource ID="GridviewSelectedRow" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OraInsuranceConnection %>" 
        ProviderName="<%$ ConnectionStrings:OraInsuranceConnection.ProviderName %>" 
        SelectCommand="select * from customer where customer_id = :customer_id" 
        UpdateCommand="update customer set first_name=:first_name, last_name=:last_name, birth_date=:birth_date, gender=:gender, address=:address, phone=:phone, email=:email where customer_id=:customer_id" 
        DeleteCommand="delete from customer where customer_id = :customer_id" 
        InsertCommand="insert into customer (customer_id, first_name, last_name, birth_date, gender, address, phone, email) values (:customer_id, :first_name, :last_name, :birth_date, :gender, :address, :phone, :email)" 
        onupdated="updateOraInsurance" ondeleted="updateOraInsurance" 
        oninserted="updateOraInsurance" onselected="updateOraInsurance">
        <SelectParameters>
            <asp:ControlParameter Name="customer_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </SelectParameters>
        <DeleteParameters>
              <asp:ControlParameter Name="customer_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter Name="customer_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="first_name" Type="String" />
            <asp:Parameter Name="last_name" Type="String" />
            <asp:Parameter Name="birth_date" Type="DateTime" />
            <asp:Parameter Name="gender" Type="Decimal" />
            <asp:Parameter Name="address" Type="String" />
            <asp:Parameter Name="phone" Type="String" />
            <asp:Parameter Name="email" Type="String" />
        </UpdateParameters>
        <InsertParameters>
            <asp:ControlParameter Name="customer_id" Type="Decimal"
              ControlID="tableGridView" PropertyName="SelectedValue" />
            <asp:Parameter Name="first_name" Type="String" />
            <asp:Parameter Name="last_name" Type="String" />
            <asp:Parameter Name="birth_date" Type="DateTime" />
            <asp:Parameter Name="gender" Type="Decimal" />
            <asp:Parameter Name="address" Type="String" />
            <asp:Parameter Name="phone" Type="String" />
            <asp:Parameter Name="email" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
</asp:Content>
